baseurl = "/"
languageCode = "en-us"
title = "Data science for students"
theme = "hugo-lithium-z"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

paginate = 5
PaginatePath = "/post/"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    

  
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Sections"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[params]
  
  description = "This is a blog created by a graduate student to share articles about data science and relevant data science and Business intelligence with the student community in the university of HEC montreal"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "dracula"

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  # path to the favicon, under "static"
  favicon = "favicon.png"

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[taxonomies]
    author="authors" 
    tag = "tags"
    category = "categories"