baseurl = "/"
languageCode = "en-us"
title = "Data science for students"
theme = "hugo-lithium-z"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate= 4
[permalinks]
    post = "/:year/:month/:day/:slug/"
    

  
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Authors"
    url = "/authors/"
    weight = 3
[[menu.main]]
    name = "Themes"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6


[params]
    

    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "dracula"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[taxonomies]
author="authors" 
tag = "tags"
category = "categories"